# Form implementation generated from reading ui file '.\Confirmation.ui'
#
# Created by: PyQt6 UI code generator 6.2.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_confirmation(object):
    def setupUi(self, confirmation):
        confirmation.setObjectName("confirmation")
        confirmation.resize(328, 240)
        font = QtGui.QFont()
        font.setPointSize(10)
        confirmation.setFont(font)
        self.verticalLayoutWidget = QtWidgets.QWidget(confirmation)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 40, 291, 141))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lblSchool = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lblSchool.setObjectName("lblSchool")
        self.horizontalLayout.addWidget(self.lblSchool)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.lblKTextCol = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lblKTextCol.setObjectName("lblKTextCol")
        self.horizontalLayout_2.addWidget(self.lblKTextCol)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_3.addWidget(self.label_6)
        self.lblEorA = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lblEorA.setObjectName("lblEorA")
        self.horizontalLayout_3.addWidget(self.lblEorA)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_4.addWidget(self.label_7)
        self.lblRTextCol = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lblRTextCol.setObjectName("lblRTextCol")
        self.horizontalLayout_4.addWidget(self.lblRTextCol)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.label_9 = QtWidgets.QLabel(confirmation)
        self.label_9.setGeometry(QtCore.QRect(20, 10, 261, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.btnConfirm = QtWidgets.QPushButton(confirmation)
        self.btnConfirm.setGeometry(QtCore.QRect(20, 190, 101, 41))
        self.btnConfirm.setObjectName("btnConfirm")
        self.btnBack = QtWidgets.QPushButton(confirmation)
        self.btnBack.setGeometry(QtCore.QRect(210, 190, 101, 41))
        self.btnBack.setObjectName("btnBack")

        self.retranslateUi(confirmation)
        QtCore.QMetaObject.connectSlotsByName(confirmation)

    def retranslateUi(self, confirmation):
        _translate = QtCore.QCoreApplication.translate
        confirmation.setWindowTitle(_translate("confirmation", "Confirmation"))
        self.label.setText(_translate("confirmation", "School:"))
        self.lblSchool.setText(_translate("confirmation", "n/a"))
        self.label_4.setText(_translate("confirmation", "Klasfoto text colour:"))
        self.lblKTextCol.setText(_translate("confirmation", "n/a"))
        self.label_6.setText(_translate("confirmation", "Graad or Grade:"))
        self.lblEorA.setText(_translate("confirmation", "n/a"))
        self.label_7.setText(_translate("confirmation", "Raam text colour:"))
        self.lblRTextCol.setText(_translate("confirmation", "n/a"))
        self.label_9.setText(_translate("confirmation", "Please confirm the folloing information:"))
        self.btnConfirm.setText(_translate("confirmation", "Confirm"))
        self.btnBack.setText(_translate("confirmation", "Back"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    confirmation = QtWidgets.QDialog()
    ui = Ui_confirmation()
    ui.setupUi(confirmation)
    confirmation.show()
    sys.exit(app.exec())
