# Form implementation generated from reading ui file '.\KlasfotoSettings.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_KlasfotoSettings(object):
    def setupUi(self, KlasfotoSettings):
        KlasfotoSettings.setObjectName("KlasfotoSettings")
        KlasfotoSettings.resize(476, 721)
        font = QtGui.QFont()
        font.setPointSize(10)
        KlasfotoSettings.setFont(font)
        self.tblSettings = QtWidgets.QTableWidget(KlasfotoSettings)
        self.tblSettings.setGeometry(QtCore.QRect(10, 40, 451, 241))
        self.tblSettings.setRowCount(0)
        self.tblSettings.setColumnCount(4)
        self.tblSettings.setObjectName("tblSettings")
        item = QtWidgets.QTableWidgetItem()
        self.tblSettings.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblSettings.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblSettings.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblSettings.setHorizontalHeaderItem(3, item)
        self.btnBack = QtWidgets.QPushButton(KlasfotoSettings)
        self.btnBack.setGeometry(QtCore.QRect(350, 660, 91, 41))
        self.btnBack.setObjectName("btnBack")
        self.btnConfirm = QtWidgets.QPushButton(KlasfotoSettings)
        self.btnConfirm.setGeometry(QtCore.QRect(50, 660, 91, 41))
        self.btnConfirm.setObjectName("btnConfirm")
        self.cbxAllGraad = QtWidgets.QCheckBox(KlasfotoSettings)
        self.cbxAllGraad.setGeometry(QtCore.QRect(140, 20, 61, 17))
        self.cbxAllGraad.setObjectName("cbxAllGraad")
        self.cbxAllGrade = QtWidgets.QCheckBox(KlasfotoSettings)
        self.cbxAllGrade.setGeometry(QtCore.QRect(250, 20, 61, 17))
        self.cbxAllGrade.setObjectName("cbxAllGrade")
        self.cbxAllNone = QtWidgets.QCheckBox(KlasfotoSettings)
        self.cbxAllNone.setGeometry(QtCore.QRect(370, 20, 61, 17))
        self.cbxAllNone.setObjectName("cbxAllNone")
        self.label = QtWidgets.QLabel(KlasfotoSettings)
        self.label.setGeometry(QtCore.QRect(60, 20, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.groupBox = QtWidgets.QGroupBox(KlasfotoSettings)
        self.groupBox.setGeometry(QtCore.QRect(20, 380, 441, 261))
        self.groupBox.setObjectName("groupBox")
        self.imgPreview = QtWidgets.QLabel(self.groupBox)
        self.imgPreview.setGeometry(QtCore.QRect(50, 40, 341, 211))
        self.imgPreview.setText("")
        self.imgPreview.setObjectName("imgPreview")
        self.groupBox_2 = QtWidgets.QGroupBox(KlasfotoSettings)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 300, 191, 61))
        self.groupBox_2.setObjectName("groupBox_2")
        self.rbtWhite = QtWidgets.QRadioButton(self.groupBox_2)
        self.rbtWhite.setGeometry(QtCore.QRect(10, 30, 82, 17))
        self.rbtWhite.setObjectName("rbtWhite")
        self.rbtBlack = QtWidgets.QRadioButton(self.groupBox_2)
        self.rbtBlack.setGeometry(QtCore.QRect(110, 30, 82, 17))
        self.rbtBlack.setObjectName("rbtBlack")

        self.retranslateUi(KlasfotoSettings)
        QtCore.QMetaObject.connectSlotsByName(KlasfotoSettings)

    def retranslateUi(self, KlasfotoSettings):
        _translate = QtCore.QCoreApplication.translate
        KlasfotoSettings.setWindowTitle(_translate("KlasfotoSettings", "Dialog"))
        item = self.tblSettings.horizontalHeaderItem(0)
        item.setText(_translate("KlasfotoSettings", "Class"))
        item = self.tblSettings.horizontalHeaderItem(1)
        item.setText(_translate("KlasfotoSettings", "Graad"))
        item = self.tblSettings.horizontalHeaderItem(2)
        item.setText(_translate("KlasfotoSettings", "Grade"))
        item = self.tblSettings.horizontalHeaderItem(3)
        item.setText(_translate("KlasfotoSettings", "None"))
        self.btnBack.setText(_translate("KlasfotoSettings", "Back"))
        self.btnConfirm.setText(_translate("KlasfotoSettings", "Confrim"))
        self.cbxAllGraad.setText(_translate("KlasfotoSettings", "Graad"))
        self.cbxAllGrade.setText(_translate("KlasfotoSettings", "Grade"))
        self.cbxAllNone.setText(_translate("KlasfotoSettings", "None"))
        self.label.setText(_translate("KlasfotoSettings", "ALL:"))
        self.groupBox.setTitle(_translate("KlasfotoSettings", "Sample"))
        self.groupBox_2.setTitle(_translate("KlasfotoSettings", "Font colour"))
        self.rbtWhite.setText(_translate("KlasfotoSettings", "White"))
        self.rbtBlack.setText(_translate("KlasfotoSettings", "Black"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    KlasfotoSettings = QtWidgets.QDialog()
    ui = Ui_KlasfotoSettings()
    ui.setupUi(KlasfotoSettings)
    KlasfotoSettings.show()
    sys.exit(app.exec())
