# Form implementation generated from reading ui file '.\RaamSettings.ui'
#
# Created by: PyQt6 UI code generator 6.2.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_raam_settings(object):
    def setupUi(self, raam_settings):
        raam_settings.setObjectName("raam_settings")
        raam_settings.resize(342, 555)
        font = QtGui.QFont()
        font.setPointSize(10)
        raam_settings.setFont(font)
        self.groupBox_3 = QtWidgets.QGroupBox(raam_settings)
        self.groupBox_3.setGeometry(QtCore.QRect(30, 10, 281, 401))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.imgPreview = QtWidgets.QLabel(self.groupBox_3)
        self.imgPreview.setGeometry(QtCore.QRect(10, 30, 261, 361))
        self.imgPreview.setText("")
        self.imgPreview.setObjectName("imgPreview")
        self.groupBox = QtWidgets.QGroupBox(raam_settings)
        self.groupBox.setGeometry(QtCore.QRect(30, 430, 281, 71))
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 30, 261, 26))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.rbtBalck = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.rbtBalck.setObjectName("rbtBalck")
        self.horizontalLayout.addWidget(self.rbtBalck)
        self.rbtWhite = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.rbtWhite.setObjectName("rbtWhite")
        self.horizontalLayout.addWidget(self.rbtWhite)
        self.btnConfirm = QtWidgets.QPushButton(raam_settings)
        self.btnConfirm.setGeometry(QtCore.QRect(110, 510, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.btnConfirm.setFont(font)
        self.btnConfirm.setObjectName("btnConfirm")

        self.retranslateUi(raam_settings)
        QtCore.QMetaObject.connectSlotsByName(raam_settings)

    def retranslateUi(self, raam_settings):
        _translate = QtCore.QCoreApplication.translate
        raam_settings.setWindowTitle(_translate("raam_settings", "Raam Settings"))
        self.groupBox_3.setTitle(_translate("raam_settings", "Raam"))
        self.groupBox.setTitle(_translate("raam_settings", "Colour of photo number"))
        self.rbtBalck.setText(_translate("raam_settings", "Black"))
        self.rbtWhite.setText(_translate("raam_settings", "White"))
        self.btnConfirm.setText(_translate("raam_settings", "Confirm"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    raam_settings = QtWidgets.QDialog()
    ui = Ui_raam_settings()
    ui.setupUi(raam_settings)
    raam_settings.show()
    sys.exit(app.exec())
