# Form implementation generated from reading ui file './UI/QtDes/RaamSettings.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_RaamSettings(object):
    def setupUi(self, RaamSetgtings):
        RaamSetgtings.setObjectName("RaamSetgtings")
        RaamSetgtings.setMinimumHeight(700)
        RaamSetgtings.setMinimumWidth(400)
        RaamSetgtings.setMaximumHeight(700)
        RaamSetgtings.setMaximumWidth(400)
        self.gridLayout = QtWidgets.QGridLayout(RaamSetgtings)
        self.gridLayout.setObjectName("gridLayout")
        self.rbtWhite = QtWidgets.QRadioButton(parent=RaamSetgtings)
        self.rbtWhite.setObjectName("rbtWhite")
        self.gridLayout.addWidget(self.rbtWhite, 3, 1, 1, 1)
        self.label = QtWidgets.QLabel(parent=RaamSetgtings)
        self.label.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)
        self.btnConfirm = QtWidgets.QPushButton(parent=RaamSetgtings)
        self.btnConfirm.setObjectName("btnConfirm")
        self.gridLayout.addWidget(self.btnConfirm, 4, 0, 1, 2)
        self.imgPreview = QtWidgets.QLabel(parent=RaamSetgtings)
        self.imgPreview.setText("")
        self.imgPreview.setObjectName("imgPreview")
        self.gridLayout.addWidget(self.imgPreview, 1, 0, 1, 2)
        self.label_3 = QtWidgets.QLabel(parent=RaamSetgtings)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 2)
        self.rbtBalck = QtWidgets.QRadioButton(parent=RaamSetgtings)
        self.rbtBalck.setObjectName("rbtBalck")
        self.gridLayout.addWidget(self.rbtBalck, 3, 0, 1, 1)

        self.retranslateUi(RaamSetgtings)
        QtCore.QMetaObject.connectSlotsByName(RaamSetgtings)

    def retranslateUi(self, RaamSetgtings):
        _translate = QtCore.QCoreApplication.translate
        RaamSetgtings.setWindowTitle(_translate("RaamSetgtings", "Dialog"))
        self.rbtWhite.setText(_translate("RaamSetgtings", "White"))
        self.label.setText(_translate("RaamSetgtings", "Raam:"))
        self.btnConfirm.setText(_translate("RaamSetgtings", "Confirm"))
        self.label_3.setText(_translate("RaamSetgtings", "Color of photo number:"))
        self.rbtBalck.setText(_translate("RaamSetgtings", "Black"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RaamSetgtings = QtWidgets.QDialog()
    ui = Ui_RaamSetgtings()
    ui.setupUi(RaamSetgtings)
    RaamSetgtings.show()
    sys.exit(app.exec())
